version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
      - "5002:5002"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  ollama_data:
