export const topics = [
  [
    "Cyclops",
    "Pegasus",
    "Medusa",
    "Sphinx",
    "Werewolf",
    "Unicorn",
    "Dragon",
    "Troll",
    "Loch Ness Monster",
    "Mermaid",
    "Phoenix",
    "Vampire",
    "Minotaur",
    "Hydra",
    "Yeti",
    "Centaur",
  ],

  [
    "Stamps",
    "Trains",
    "Model Making",
    "Knitting",
    "Fishing",
    "Reading",
    "Painting",
    "Gardening",
    "Sailing",
    "Travel",
    "Walking",
    "Pottery",
    "Cooking",
    "Yoga",
    "Photography",
    "Hiking",
  ],

  [
    "Octopus",
    "Starfish",
    "Shark",
    "Jellyfish",
    "Lobster",
    "Seal",
    "Dolphin",
    "Killer Whale",
    "Crab",
    "Giant Squid",
    "Seahorse",
    "Stingray",
    "Sea Turtle",
    "Clownfish",
    "Swordfish",
    "Mermaid",
  ],

  [
    "New York City",
    "Moscow",
    "Delhi",
    "London",
    "Paris",
    "Rome",
    "Rio de Janeiro",
    "Sydney",
    "Tokyo",
    "Athens",
    "Cairo",
    "Hong Kong",
    "Chicago",
    "L.A.",
    "San Francisco",
    "Jerusalem",
  ],

  [
    "Planets",
    "Stars",
    "Galaxies",
    "Black Holes",
    "Asteroids",
    "Comets",
    "Satellites",
    "Nebulae",
    "Moons",
    "Space Stations",
    "Space Probes",
    "Meteorites",
    "Astronauts",
    "Telescopes",
    "Rockets",
    "Aliens",
  ],

  [
    "Cats",
    "Dogs",
    "Hamsters",
    "Parrots",
    "Fish",
    "Guinea Pigs",
    "Lizards",
    "Turtles",
    "Snakes",
    "Frogs",
    "Ferrets",
    "Rabbits",
    "Hedgehogs",
    "Chinchillas",
    "Horses",
    "Geckos",
  ],

  [
    "Pineapple",
    "Apple",
    "Banana",
    "Orange",
    "Grapes",
    "Mango",
    "Strawberry",
    "Blueberry",
    "Peach",
    "Pear",
    "Watermelon",
    "Cantaloupe",
    "Papaya",
    "Kiwi",
    "Lime",
    "Coconut",
  ],

  [
    "Soccer",
    "Basketball",
    "Baseball",
    "Tennis",
    "Golf",
    "Hockey",
    "Cricket",
    "Rugby",
    "Volleyball",
    "Swimming",
    "Cycling",
    "Boxing",
    "Gymnastics",
    "Track and Field",
    "Skiing",
    "Snowboarding",
  ],

  [
    "Carrots",
    "Potatoes",
    "Onions",
    "Tomatoes",
    "Cucumbers",
    "Peppers",
    "Spinach",
    "Lettuce",
    "Broccoli",
    "Cauliflower",
    "Eggplant",
    "Zucchini",
    "Celery",
    "Garlic",
    "Radishes",
    "Mushrooms",
  ],

  [
    "Mountains",
    "Rivers",
    "Oceans",
    "Forests",
    "Deserts",
    "Lakes",
    "Waterfalls",
    "Caves",
    "Valleys",
    "Cliffs",
    "Glaciers",
    "Islands",
    "Fjords",
    "Plains",
    "Volcanoes",
    "Swamps",
  ],

  [
    "Ford",
    "Toyota",
    "Honda",
    "Chevrolet",
    "Nissan",
    "BMW",
    "Mercedes",
    "Tesla",
    "Audi",
    "Hyundai",
    "Kia",
    "Volkswagen",
    "Jeep",
    "Subaru",
    "Mazda",
    "Volvo",
  ],

  [
    "Python",
    "Java",
    "C++",
    "JavaScript",
    "Ruby",
    "Swift",
    "Go",
    "PHP",
    "C#",
    "R",
    "SQL",
    "MATLAB",
    "Perl",
    "TypeScript",
    "Rust",
    "Kotlin",
  ],

  [
    "Mozart",
    "Beethoven",
    "Bach",
    "Chopin",
    "Tchaikovsky",
    "Vivaldi",
    "Handel",
    "Debussy",
    "Ravel",
    "Schumann",
    "Brahms",
    "Liszt",
    "Haydn",
    "Mahler",
    "Strauss",
    "Wagner",
  ],

  [
    "Shakespeare",
    "Hemingway",
    "Austen",
    "Orwell",
    "Tolkien",
    "Dickens",
    "Poe",
    "Homer",
    "Dostoevsky",
    "Kafka",
    "Steinbeck",
    "Fitzgerald",
    "Joyce",
    "Woolf",
    "Chekhov",
    "Whitman",
  ],

  [
    "Physics",
    "Chemistry",
    "Biology",
    "Astronomy",
    "Geology",
    "Mathematics",
    "Psychology",
    "Sociology",
    "Anthropology",
    "Economics",
    "Political Science",
    "Linguistics",
    "History",
    "Philosophy",
    "Archaeology",
    "Ecology",
  ],

  [
    "Butterflies",
    "Bees",
    "Ants",
    "Spiders",
    "Dragonflies",
    "Ladybugs",
    "Grasshoppers",
    "Crickets",
    "Moths",
    "Beetles",
    "Flies",
    "Mosquitoes",
    "Wasps",
    "Cockroaches",
    "Caterpillars",
    "Termites",
  ],

  [
    "Piano",
    "Guitar",
    "Violin",
    "Drums",
    "Flute",
    "Saxophone",
    "Trumpet",
    "Clarinet",
    "Cello",
    "Harp",
    "Trombone",
    "Oboe",
    "Bassoon",
    "Accordion",
    "Ukulele",
    "Banjo",
  ],

  [
    "Chess",
    "Checkers",
    "Scrabble",
    "Monopoly",
    "Clue",
    "Risk",
    "Settlers of Catan",
    "Pandemic",
    "Ticket to Ride",
    "Codenames",
    "Carcassonne",
    "Dominion",
    "Twilight Struggle",
    "7 Wonders",
    "Azul",
    "Dixit",
  ],

  [
    "Burgers",
    "Pizza",
    "Pasta",
    "Tacos",
    "Sushi",
    "Steak",
    "Salad",
    "Soup",
    "Fries",
    "Ice Cream",
    "Sandwiches",
    "Pancakes",
    "Waffles",
    "Curry",
    "Ramen",
    "Kebabs",
  ],

  [
    "USA",
    "Canada",
    "Mexico",
    "Brazil",
    "UK",
    "France",
    "Germany",
    "Italy",
    "Spain",
    "China",
    "Japan",
    "India",
    "Russia",
    "Australia",
    "South Africa",
    "Argentina",
  ],

  [
    "Red",
    "Blue",
    "Green",
    "Yellow",
    "Purple",
    "Orange",
    "Black",
    "White",
    "Gray",
    "Brown",
    "Pink",
    "Cyan",
    "Magenta",
    "Teal",
    "Maroon",
    "Lavender",
  ],

  [
    "Hammer",
    "Screwdriver",
    "Wrench",
    "Pliers",
    "Drill",
    "Saw",
    "Chisel",
    "Level",
    "Tape Measure",
    "Utility Knife",
    "Clamp",
    "Sander",
    "Mallet",
    "Allen Key",
    "Socket",
    "Awl",
  ],

  [
    "English",
    "Mathematics",
    "Science",
    "History",
    "Geography",
    "Art",
    "Music",
    "Physical Education",
    "Computer Science",
    "Economics",
    "Biology",
    "Chemistry",
    "Physics",
    "Literature",
    "Philosophy",
    "Sociology",
  ],

  [
    "Teacher",
    "Doctor",
    "Engineer",
    "Lawyer",
    "Chef",
    "Artist",
    "Programmer",
    "Nurse",
    "Mechanic",
    "Farmer",
    "Pilot",
    "Musician",
    "Architect",
    "Journalist",
    "Pharmacist",
    "Accountant",
  ],

  [
    "Rock",
    "Pop",
    "Jazz",
    "Blues",
    "Classical",
    "Country",
    "Hip-Hop",
    "Rap",
    "R&B",
    "Reggae",
    "Electronic",
    "Funk",
    "Soul",
    "Metal",
    "Gospel",
    "Folk",
  ],

  [
    "Waltz",
    "Tango",
    "Salsa",
    "Ballet",
    "Hip-Hop",
    "Breakdance",
    "Foxtrot",
    "Cha-Cha",
    "Rumba",
    "Paso Doble",
    "Samba",
    "Merengue",
    "Tap",
    "Jazz",
    "Swing",
    "Flamenco",
  ],

  [
    "Mickey Mouse",
    "Bugs Bunny",
    "Tom",
    "Jerry",
    "Scooby-Doo",
    "Donald Duck",
    "Goofy",
    "Tweety",
    "Sylvester",
    "Daffy Duck",
    "SpongeBob",
    "Patrick Star",
    "Bart Simpson",
    "Homer Simpson",
    "Fred Flintstone",
    "Popeye",
  ],

  [
    "Super Mario",
    "The Legend of Zelda",
    "Pokémon",
    "Final Fantasy",
    "Call of Duty",
    "Assassin's Creed",
    "Halo",
    "Street Fighter",
    "Tekken",
    "Minecraft",
    "Fortnite",
    "Metal Gear",
    "Resident Evil",
    "Silent Hill",
    "Grand Theft Auto",
    "World of Warcraft",
  ],

  [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Angular",
    "Vue",
    "Node.js",
    "Django",
    "Ruby on Rails",
    "Laravel",
    "ASP.NET",
    "GraphQL",
    "jQuery",
    "Ajax",
    "Sass",
    "Bootstrap",
  ],

  [
    "Nike",
    "Adidas",
    "Puma",
    "Reebok",
    "Under Armour",
    "New Balance",
    "ASICS",
    "Converse",
    "Vans",
    "Skechers",
    "Fila",
    "Salomon",
    "Timberland",
    "Birkenstock",
    "Crocs",
    "Merrell",
  ],

  [
    "Shirt",
    "Pants",
    "Skirt",
    "Dress",
    "Jacket",
    "Coat",
    "Sweater",
    "T-Shirt",
    "Shorts",
    "Socks",
    "Tie",
    "Scarf",
    "Hat",
    "Gloves",
    "Belt",
    "Blouse",
  ],

  [
    "Pepperoni",
    "Mushrooms",
    "Onions",
    "Sausage",
    "Bacon",
    "Extra Cheese",
    "Black Olives",
    "Green Peppers",
    "Pineapple",
    "Ham",
    "Spinach",
    "Garlic",
    "Tomatoes",
    "Feta Cheese",
    "Chicken",
    "Basil",
  ],

  [
    "Fish and Chips",
    "Grilled Salmon",
    "Shrimp Cocktail",
    "Lobster Bisque",
    "Crab Cakes",
    "Oysters Rockefeller",
    "Paella",
    "Ceviche",
    "Sushi Rolls",
    "Clam Chowder",
    "Seafood Linguine",
    "Mussels Marinara",
    "Fried Calamari",
    "Scallop Risotto",
    "Tuna Tartare",
    "Shrimp Scampi",
  ],

  [
    "French Revolution",
    "American Revolution",
    "World War I",
    "World War II",
    "Fall of Rome",
    "Renaissance",
    "Industrial Revolution",
    "Discovery of America",
    "Russian Revolution",
    "Protestant Reformation",
    "Magna Carta Signing",
    "Women's Suffrage",
    "Moon Landing",
    "Berlin Wall Fall",
    "9/11 Attacks",
    "Arab Spring",
  ],

  [
    "Julius Caesar",
    "Napoleon",
    "Abraham Lincoln",
    "George Washington",
    "Martin Luther King Jr.",
    "Mahatma Gandhi",
    "Winston Churchill",
    "Nelson Mandela",
    "Cleopatra",
    "Joan of Arc",
    "Leonardo da Vinci",
    "Michelangelo",
    "Albert Einstein",
    "Marie Curie",
    "Mother Teresa",
    "Rosa Parks",
  ],

  [
    "Tail",
    "Fur",
    "Horns",
    "Tusks",
    "Beak",
    "Feathers",
    "Scales",
    "Wings",
    "Fins",
    "Gills",
    "Hooves",
    "Claws",
    "Antlers",
    "Snout",
    "Whiskers",
    "Shell",
  ],

  [
    "Heart",
    "Lungs",
    "Brain",
    "Kidneys",
    "Liver",
    "Stomach",
    "Pancreas",
    "Intestines",
    "Gallbladder",
    "Spleen",
    "Appendix",
    "Bladder",
    "Thyroid",
    "Adrenal Glands",
    "Uterus",
    "Prostate",
  ],

  [
    "Engine",
    "Transmission",
    "Brakes",
    "Wheels",
    "Tires",
    "Battery",
    "Radiator",
    "Alternator",
    "Spark Plugs",
    "Exhaust",
    "Dashboard",
    "Seats",
    "Air Filter",
    "Headlights",
    "Bumpers",
    "Windshield",
  ],

  [
    "Louis Armstrong",
    "Miles Davis",
    "John Coltrane",
    "Duke Ellington",
    "Charlie Parker",
    "Ella Fitzgerald",
    "Billie Holiday",
    "Thelonious Monk",
    "Count Basie",
    "Stan Getz",
    "Dizzy Gillespie",
    "Herbie Hancock",
    "Chick Corea",
    "Wynton Marsalis",
    "Nina Simone",
    "Sarah Vaughan",
  ],

  [
    "Maria Callas",
    "Luciano Pavarotti",
    "Joan Sutherland",
    "Plácido Domingo",
    "Montserrat Caballé",
    "José Carreras",
    "Renata Tebaldi",
    "Leontyne Price",
    "Beverly Sills",
    "Kiri Te Kanawa",
    "Cecilia Bartoli",
    "Anna Netrebko",
    "Renee Fleming",
    "Dmitri Hvorostovsky",
    "Jonas Kaufmann",
    "Elina Garanca",
  ],

  [
    "Autumn Leaves",
    "All the Things You Are",
    "Summertime",
    "My Funny Valentine",
    "Take the A Train",
    "Fly Me to the Moon",
    "Misty",
    "All of Me",
    "Stella by Starlight",
    "'Round Midnight",
    "Blue Monk",
    "Body and Soul",
    "Georgia on My Mind",
    "In a Sentimental Mood",
    "Satin Doll",
    "Sophisticated Lady",
  ],

  [
    "The Beatles",
    "The Rolling Stones",
    "Led Zeppelin",
    "Pink Floyd",
    "Queen",
    "AC/DC",
    "Nirvana",
    "The Who",
    "Metallica",
    "Guns N' Roses",
    "U2",
    "Aerosmith",
    "Black Sabbath",
    "Deep Purple",
    "Eagles",
    "Fleetwood Mac",
  ],

  [
    "Unison",
    "Minor Second",
    "Major Second",
    "Minor Third",
    "Major Third",
    "Perfect Fourth",
    "Tritone",
    "Perfect Fifth",
    "Minor Sixth",
    "Major Sixth",
    "Minor Seventh",
    "Major Seventh",
    "Octave",
    "Minor Ninth",
    "Major Ninth",
    "Perfect Eleventh",
  ],

  [
    "Alpha",
    "Beta",
    "Gamma",
    "Delta",
    "Epsilon",
    "Zeta",
    "Eta",
    "Theta",
    "Iota",
    "Kappa",
    "Lambda",
    "Mu",
    "Nu",
    "Xi",
    "Omicron",
    "Pi",
  ],

  [
    "C Major",
    "G Major",
    "D Major",
    "A Major",
    "E Major",
    "B Major",
    "F# Major",
    "C# Major",
    "F Major",
    "Bb Major",
    "Eb Major",
    "Ab Major",
    "Db Major",
    "Gb Major",
    "Cb Major",
    "C Minor",
  ],

  [
    "Ahoy",
    "Arrr",
    "Matey",
    "Buccaneer",
    "Swashbuckler",
    "Treasure",
    "Jolly Roger",
    "Pirate Ship",
    "Plunder",
    "Maroon",
    "Mutiny",
    "Sea Shanty",
    "Grog",
    "Parrot",
    "Hook",
    "Deck",
  ],

  [
    "Battlefield",
    "Infantry",
    "Artillery",
    "Cavalry",
    "Trench",
    "Siege",
    "Armistice",
    "Air Strike",
    "Naval Fleet",
    "Ambush",
    "Guerrilla Warfare",
    "Allies",
    "Axis",
    "Sniper",
    "Camouflage",
    "Peace Treaty",
  ],

  [
    "Defendant",
    "Plaintiff",
    "Testimony",
    "Deposition",
    "Subpoena",
    "Verdict",
    "Appeal",
    "Habeas Corpus",
    "Injunction",
    "Liability",
    "Negligence",
    "Contract",
    "Tort",
    "Arbitration",
    "Settlement",
    "Jury",
  ],

  [
    "Cardiology",
    "Neurology",
    "Oncology",
    "Pediatrics",
    "Orthopedics",
    "Dermatology",
    "Psychiatry",
    "Ophthalmology",
    "Gynecology",
    "Gastroenterology",
    "Urology",
    "Nephrology",
    "Endocrinology",
    "Rheumatology",
    "Hematology",
    "Anesthesiology",
  ],

  [
    "Procedural",
    "Object-Oriented",
    "Functional",
    "Declarative",
    "Imperative",
    "Event-Driven",
    "Generic",
    "Aspect-Oriented",
    "Reactive",
    "Concurrent",
    "Distributed",
    "Logic",
    "Component-Based",
    "Metaprogramming",
    "Constraint",
    "Structured",
  ],

  [
    "Coca-Cola",
    "Pepsi",
    "Sprite",
    "Fanta",
    "Mountain Dew",
    "Dr Pepper",
    "7 Up",
    "Root Beer",
    "Ginger Ale",
    "Club Soda",
    "Tonic Water",
    "Cream Soda",
    "Orange Crush",
    "Grape Soda",
    "Barq's",
    "Inca Kola",
  ],

  [
    "Vanilla",
    "Chocolate",
    "Strawberry",
    "Mint Chocolate Chip",
    "Cookies and Cream",
    "Rocky Road",
    "Butter Pecan",
    "Neapolitan",
    "Pistachio",
    "Cookie Dough",
    "Salted Caramel",
    "Mango Sorbet",
    "Chocolate Chip",
    "Moose Tracks",
    "Cotton Candy",
    "Birthday Cake",
  ],

  [
    "Chocolate Bar",
    "Gummy Bears",
    "Licorice",
    "Candy Canes",
    "Lollipops",
    "Candy Corn",
    "Sour Gummies",
    "Jelly Beans",
    "Hard Candy",
    "Peanut Butter Cups",
    "Toffee",
    "Truffles",
    "Fudge",
    "Taffy",
    "Caramel",
    "Butterscotch",
  ],

  [
    "Lego",
    "Barbie",
    "Hot Wheels",
    "Fisher-Price",
    "Play-Doh",
    "Nerf",
    "Transformers",
    "My Little Pony",
    "Little Tikes",
    "Mega Bloks",
    "Hasbro",
    "Mattel",
    "Funko",
    "Bruder",
    "Tonka",
    "Melissa & Doug",
  ],

  [
    "Mona Lisa",
    "The Starry Night",
    "Girl with a Pearl Earring",
    "The Persistence of Memory",
    "Guernica",
    "The Scream",
    "American Gothic",
    "Nighthawks",
    "Las Meninas",
    "The Kiss",
    "Sunflowers",
    "The Birth of Venus",
    "Water Lilies",
    "Cafe Terrace at Night",
    "Liberty Leading the People",
    "The Garden of Earthly Delights",
  ],

  [
    "Zeus",
    "Hera",
    "Poseidon",
    "Demeter",
    "Athena",
    "Apollo",
    "Artemis",
    "Ares",
    "Aphrodite",
    "Hephaestus",
    "Hermes",
    "Dionysus",
    "Hestia",
    "Eros",
    "Persephone",
    "Hades",
  ],

  [
    "Jupiter",
    "Juno",
    "Neptune",
    "Ceres",
    "Minerva",
    "Apollo",
    "Diana",
    "Mars",
    "Venus",
    "Vulcan",
    "Mercury",
    "Bacchus",
    "Vesta",
    "Cupid",
    "Proserpina",
    "Pluto",
  ],

  [
    "Ra",
    "Osiris",
    "Isis",
    "Horus",
    "Set",
    "Nephthys",
    "Anubis",
    "Bastet",
    "Thoth",
    "Hathor",
    "Sekhmet",
    "Sobek",
    "Geb",
    "Nut",
    "Ma'at",
    "Amun",
  ],

  [
    "Odin",
    "Frigg",
    "Thor",
    "Loki",
    "Baldur",
    "Freya",
    "Frey",
    "Tyr",
    "Heimdall",
    "Bragi",
    "Idun",
    "Njord",
    "Skadi",
    "Hel",
    "Vidar",
    "Vali",
  ],

  [
    "Olodumare",
    "Olorun",
    "Olofi",
    "Obatala",
    "Orunmila",
    "Shango",
    "Oshun",
    "Yemoja",
    "Oya",
    "Ogun",
    "Elegua",
    "Babalu Aye",
    "Ochosi",
    "Osanyin",
    "Agayu",
    "Erinle",
  ],

  [
    "Atlantis",
    "El Dorado",
    "Shangri-La",
    "Camelot",
    "Avalon",
    "Xanadu",
    "Valhalla",
    "Asgard",
    "Olympus",
    "Agartha",
    "Lyonesse",
    "R'lyeh",
    "Hy-Brasil",
    "Kunlun",
    "Meropis",
    "Cibola",
  ],

  [
    "100m Dash",
    "Marathon",
    "High Jump",
    "Long Jump",
    "Discus Throw",
    "Shot Put",
    "Javelin Throw",
    "Pole Vault",
    "Gymnastics All-Around",
    "Swimming Freestyle",
    "Diving Platform",
    "Basketball",
    "Soccer",
    "Volleyball",
    "Tennis Singles",
    "Wrestling",
  ],

  [
    "Battle of Stalingrad",
    "Battle of Midway",
    "Battle of Normandy",
    "Battle of the Bulge",
    "Battle of Britain",
    "Battle of Kursk",
    "Battle of Berlin",
    "Battle of Guadalcanal",
    "Battle of Iwo Jima",
    "Battle of El Alamein",
    "Battle of Okinawa",
    "Operation Market Garden",
    "Battle of Monte Cassino",
    "Battle of Tarawa",
    "Battle of France",
    "Battle of Warsaw",
  ],

  [
    "Shares",
    "Bonds",
    "IPO",
    "Dividend",
    "Bull Market",
    "Bear Market",
    "Margin",
    "Short Selling",
    "Blue Chip",
    "Portfolio",
    "Index",
    "ETF",
    "Mutual Fund",
    "Liquidity",
    "Volatility",
    "Market Cap",
  ],

  [
    "Oak",
    "Maple",
    "Pine",
    "Birch",
    "Aspen",
    "Willow",
    "Cedar",
    "Spruce",
    "Redwood",
    "Sequoia",
    "Cherry",
    "Magnolia",
    "Palm",
    "Cypress",
    "Beech",
    "Poplar",
  ],

  [
    "Wood",
    "Metal",
    "Plastic",
    "Glass",
    "Ceramic",
    "Paper",
    "Rubber",
    "Leather",
    "Cotton",
    "Wool",
    "Silk",
    "Concrete",
    "Steel",
    "Aluminum",
    "Copper",
    "Brass",
  ],

  [
    "George Washington",
    "John Adams",
    "Thomas Jefferson",
    "Abraham Lincoln",
    "Theodore Roosevelt",
    "Woodrow Wilson",
    "Franklin D. Roosevelt",
    "Harry S. Truman",
    "Dwight D. Eisenhower",
    "John F. Kennedy",
    "Lyndon B. Johnson",
    "Richard Nixon",
    "Ronald Reagan",
    "Bill Clinton",
    "Barack Obama",
    "Donald Trump",
  ],

  [
    "Bow",
    "Arrow",
    "Quiver",
    "Fletching",
    "Nock",
    "Draw Weight",
    "Anchor Point",
    "Bowstring",
    "Release",
    "Target",
    "Bullseye",
    "Compound Bow",
    "Recurve Bow",
    "Longbow",
    "Crossbow",
    "Arrow Rest",
  ],

  [
    "Atom",
    "Molecule",
    "Ion",
    "Compound",
    "Element",
    "Electron",
    "Proton",
    "Neutron",
    "Valence",
    "pH",
    "Acid",
    "Base",
    "Oxidation",
    "Reduction",
    "Catalyst",
    "Isotope",
  ],

  [
    "Force",
    "Energy",
    "Momentum",
    "Velocity",
    "Acceleration",
    "Gravity",
    "Electromagnetism",
    "Quantum Mechanics",
    "Relativity",
    "Mass",
    "Work",
    "Power",
    "Wave",
    "Particle",
    "Photon",
    "Friction",
  ],

  [
    "Supernova",
    "Light-Year",
    "Red Giant",
    "White Dwarf",
    "Neutron Star",
    "Quasar",
    "Pulsar",
    "Event Horizon",
    "Eclipse",
    "Galaxy Cluster",
    "Dark Matter",
    "Dark Energy",
    "Cosmic Microwave Background",
    "Exoplanet",
    "Cosmos",
    "Orbit",
  ],

  [
    "Spaghetti",
    "Linguine",
    "Fettuccine",
    "Penne",
    "Rigatoni",
    "Macaroni",
    "Lasagna",
    "Farfalle",
    "Rotini",
    "Cavatappi",
    "Cannelloni",
    "Ziti",
    "Orecchiette",
    "Gnocchi",
    "Ravioli",
    "Tortellini",
  ],

  [
    "Eagle",
    "Hawk",
    "Falcon",
    "Owl",
    "Sparrow",
    "Robin",
    "Blue Jay",
    "Cardinal",
    "Woodpecker",
    "Crow",
    "Dove",
    "Pigeon",
    "Hummingbird",
    "Pelican",
    "Penguin",
    "Parrot",
  ],

  [
    "Crocodile",
    "Alligator",
    "Komodo Dragon",
    "Green Iguana",
    "Garter Snake",
    "Python",
    "Cobra",
    "Chameleon",
    "Gecko",
    "Monitor Lizard",
    "Tortoise",
    "Sea Turtle",
    "Gila Monster",
    "Bearded Dragon",
    "Viper",
    "Boa Constrictor",
  ],

  [
    "Elephant",
    "Lion",
    "Tiger",
    "Leopard",
    "Giraffe",
    "Zebra",
    "Hippopotamus",
    "Rhinoceros",
    "Buffalo",
    "Gorilla",
    "Chimpanzee",
    "Orangutan",
    "Koala",
    "Kangaroo",
    "Panda",
    "Sloth",
  ],

  [
    "Poker",
    "Blackjack",
    "Bridge",
    "Hearts",
    "Spades",
    "Gin Rummy",
    "Crazy Eights",
    "UNO",
    "Baccarat",
    "Euchre",
    "Cribbage",
    "Pinochle",
    "Old Maid",
    "Go Fish",
    "Solitaire",
    "Texas Hold'em",
  ],

  [
    "Coffee",
    "Tea",
    "Hot Chocolate",
    "Espresso",
    "Latte",
    "Cappuccino",
    "Mocha",
    "Matcha",
    "Chai Latte",
    "Herbal Tea",
    "Americano",
    "Macchiato",
    "Turkish Coffee",
    "Green Tea",
    "Hot Toddy",
    "Mulled Wine",
  ],

  [
    "Christmas",
    "New Year",
    "Halloween",
    "Thanksgiving",
    "Easter",
    "Hanukkah",
    "Diwali",
    "Ramadan",
    "Passover",
    "Kwanzaa",
    "Valentine's Day",
    "St. Patrick's Day",
    "Independence Day",
    "Labor Day",
    "Mother's Day",
    "Father's Day",
  ],

  [
    "Father",
    "Mother",
    "Son",
    "Daughter",
    "Brother",
    "Sister",
    "Uncle",
    "Aunt",
    "Nephew",
    "Niece",
    "Cousin",
    "Grandfather",
    "Grandmother",
    "Great-Grandparent",
    "Spouse",
    "Sibling",
  ],

  [
    "Facebook",
    "Twitter",
    "Instagram",
    "LinkedIn",
    "Snapchat",
    "TikTok",
    "Pinterest",
    "Reddit",
    "Tumblr",
    "WeChat",
    "QQ",
    "WhatsApp",
    "Telegram",
    "YouTube",
    "Vimeo",
    "Twitch",
  ],

  [
    "Orion",
    "Ursa Major",
    "Ursa Minor",
    "Cassiopeia",
    "Cygnus",
    "Lyra",
    "Scorpius",
    "Sagittarius",
    "Taurus",
    "Gemini",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Aquarius",
    "Pisces",
  ],

  [
    "Iron Man",
    "Captain America",
    "Thor",
    "Hulk",
    "Black Widow",
    "Hawkeye",
    "Spider-Man",
    "Wolverine",
    "Professor X",
    "Magneto",
    "Storm",
    "Cyclops",
    "Jean Grey",
    "Scarlet Witch",
    "Vision",
    "Black Panther",
  ],

  [
    "Batman",
    "Superman",
    "Wonder Woman",
    "Flash",
    "Green Lantern",
    "Aquaman",
    "Cyborg",
    "Joker",
    "Harley Quinn",
    "Lex Luthor",
    "Catwoman",
    "Robin",
    "Nightwing",
    "Poison Ivy",
    "Penguin",
    "Riddler",
  ],

  [
    "Snow White",
    "Cinderella",
    "Sleeping Beauty",
    "The Little Mermaid",
    "Beauty and the Beast",
    "Aladdin",
    "The Lion King",
    "Mulan",
    "Tangled",
    "Frozen",
    "Moana",
    "Zootopia",
    "Lilo & Stitch",
    "Bambi",
    "Pinocchio",
    "Dumbo",
  ],

  [
    "Jingle Bells",
    "Silent Night",
    "O Holy Night",
    "Joy to the World",
    "Deck the Halls",
    "We Wish You a Merry Christmas",
    "Hark! The Herald Angels Sing",
    "White Christmas",
    "O Come All Ye Faithful",
    "Frosty the Snowman",
    "Rudolph the Red-Nosed Reindeer",
    "Jingle Bell Rock",
    "Winter Wonderland",
    "All I Want for Christmas Is You",
    "Santa Baby",
    "The First Noel",
  ],

  [
    "Noun",
    "Verb",
    "Adjective",
    "Adverb",
    "Pronoun",
    "Preposition",
    "Conjunction",
    "Interjection",
    "Clause",
    "Phrase",
    "Subject",
    "Predicate",
    "Article",
    "Tense",
    "Gerund",
    "Participle",
  ],

  [
    "Democracy",
    "Republicanism",
    "Socialism",
    "Communism",
    "Fascism",
    "Monarchy",
    "Anarchism",
    "Liberalism",
    "Conservatism",
    "Libertarianism",
    "Nationalism",
    "Populism",
    "Environmentalism",
    "Feminism",
    "Theocracy",
    "Oligarchy",
  ],

  [
    "Diamond",
    "Ruby",
    "Sapphire",
    "Emerald",
    "Topaz",
    "Amethyst",
    "Aquamarine",
    "Opal",
    "Pearl",
    "Tanzanite",
    "Turquoise",
    "Garnet",
    "Jade",
    "Onyx",
    "Citrine",
    "Tourmaline",
  ],

  [
    "Downward Dog",
    "Mountain Pose",
    "Warrior I",
    "Warrior II",
    "Triangle Pose",
    "Tree Pose",
    "Child's Pose",
    "Cobra Pose",
    "Bridge Pose",
    "Chair Pose",
    "Camel Pose",
    "Plank Pose",
    "Boat Pose",
    "Crow Pose",
    "Corpse Pose",
    "Eagle Pose",
  ],

  [
    "Chocolate Cake",
    "Cheesecake",
    "Apple Pie",
    "Brownies",
    "Cupcakes",
    "Ice Cream Sundae",
    "Pudding",
    "Tiramisu",
    "Crème Brûlée",
    "Baklava",
    "Gelato",
    "Fruit Salad",
    "Pavlova",
    "Macarons",
    "Churros",
    "Panna Cotta",
  ],

  [
    "Mortgage",
    "Appraisal",
    "Deed",
    "Title",
    "Escrow",
    "Equity",
    "Foreclosure",
    "Closing Costs",
    "Home Inspection",
    "Listing",
    "Realtor",
    "Down Payment",
    "Refinance",
    "Brokerage",
    "HOA Fees",
    "Amortization",
  ],

  [
    "Sweet and Sour Pork",
    "Kung Pao Chicken",
    "Mapo Tofu",
    "Dumplings",
    "Wonton Soup",
    "Chow Mein",
    "Peking Duck",
    "Hot and Sour Soup",
    "Spring Rolls",
    "Fried Rice",
    "Egg Foo Young",
    "Char Siu",
    "Dim Sum",
    "Beef and Broccoli",
    "Scallion Pancakes",
    "Dan Dan Noodles",
  ],

  [
    "Tightrope Walking",
    "Trapeze",
    "Clowning",
    "Juggling",
    "Lion Taming",
    "Acrobatics",
    "Human Cannonball",
    "Unicycling",
    "Fire Breathing",
    "Sword Swallowing",
    "Contortion",
    "Balancing Act",
    "Plate Spinning",
    "Aerial Silk",
    "Wheel of Death",
    "Magician",
  ],

  [
    "Stand-Up Comedy",
    "Sketch Comedy",
    "Improv Comedy",
    "Romantic Comedy",
    "Dark Comedy",
    "Slapstick",
    "Satire",
    "Parody",
    "Screwball Comedy",
    "Black Comedy",
    "Mockumentary",
    "Sitcom",
    "Musical Comedy",
    "Comedy of Errors",
    "Farce",
    "Comedy of Manners",
  ],

  [
    "Dodo",
    "Passenger Pigeon",
    "Tasmanian Tiger",
    "Megalodon",
    "Woolly Mammoth",
    "Saber-Toothed Tiger",
    "Great Auk",
    "Moa",
    "Steller's Sea Cow",
    "Irish Elk",
    "Quagga",
    "Carolina Parakeet",
    "Elephant Bird",
    "Pyrenean Ibex",
    "Atlas Bear",
    "Falkland Islands Wolf",
  ],

  [
    "Mesopotamia",
    "Ancient Egypt",
    "Indus Valley",
    "Mayan",
    "Aztec",
    "Inca",
    "Ancient Greece",
    "Ancient Rome",
    "Persian Empire",
    "Babylonian",
    "Hittite",
    "Minoan",
    "Phoenician",
    "Carthaginian",
    "Nubian",
    "Olmec",
  ],

  [
    "Plato",
    "Aristotle",
    "Socrates",
    "Confucius",
    "Laozi",
    "Rene Descartes",
    "Immanuel Kant",
    "Friedrich Nietzsche",
    "John Locke",
    "Thomas Hobbes",
    "Jean-Jacques Rousseau",
    "David Hume",
    "Karl Marx",
    "Simone de Beauvoir",
    "Ludwig Wittgenstein",
    "Michel Foucault",
  ],

  [
    "Troposphere",
    "Stratosphere",
    "Mesosphere",
    "Thermosphere",
    "Exosphere",
    "Ionosphere",
    "Ozone Layer",
    "Tropopause",
    "Stratopause",
    "Mesopause",
    "Thermopause",
    "Kármán Line",
    "Homosphere",
    "Heterosphere",
    "Magnetosphere",
    "Aurora Zone",
  ],

  [
    "Adenine",
    "Thymine",
    "Guanine",
    "Cytosine",
    "Double Helix",
    "Sugar-Phosphate Backbone",
    "Nucleotide",
    "Gene",
    "Genome",
    "Base Pair",
    "Chromosome",
    "Replication",
    "Transcription",
    "Translation",
    "RNA",
    "Mutation",
  ],

  [
    "The Phantom of the Opera",
    "Les Misérables",
    "Hamilton",
    "The Lion King",
    "Wicked",
    "Cats",
    "Chicago",
    "My Fair Lady",
    "West Side Story",
    "Mamma Mia!",
    "Rent",
    "Grease",
    "Hairspray",
    "The Sound of Music",
    "Sweeney Todd",
    "Oliver!",
  ],
];
